---
language: node_js
node_js:
  - 12.17.0
sudo: false
dist: xenial

addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
before_install:
  - npm --version
  - node --version
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_NPM_AUTH_TOKEN
install:
  - npm install
script:
  - npm run lint:hbs
  - npm run lint:js
  - npm run lint:sass
  - npm run test:travis
after_success:
  - npm run coveralls
